# -*- coding: utf-8 -*-
"""tutorial_education.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVsxfFV41MWIUkSpDRu9IuFYFWyOT1kR
"""

# ============================================================
# Toryum 232 Dönüşümünün İstatistiksel Modellemesi
# Eğitim Amaçlı Veri Bilimi Projesi
# ============================================================
# Yürütücü Adayı: Yusuf Erim Yaşar
# Proje Fikir Sahibi ve Gönüllüsü: Meriç Özcan
# ------------------------------------------------------------
# Amaç:
# Toryum-232 → Protaktinyum-233 → Uranyum-233 dönüşüm zincirini
# sadece sentetik veriler ve istatistiksel modelleme teknikleriyle
# temsil eden bir eğitim simülasyonu oluşturmaktır.
# Gerçek nükleer deney, üretim veya işlem içermez.
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

# ============================================================
# 1. SENTETİK VERİ OLUŞTURMA
# ============================================================

def create_synthetic_data():
    np.random.seed(42)
    t = np.arange(0, 200)
    true_signal = np.linspace(100, 700, 200)
    background = np.full(200, 7)
    counts = np.random.poisson(lam=true_signal + background)

    df = pd.DataFrame({
        "t": t,
        "counts": counts,
        "true_signal": true_signal,
        "background": background
    })
    df.to_csv("synthetic_counts.csv", index=False)
    print("✅ Sentetik veri oluşturuldu: synthetic_counts.csv")
    return df

# ============================================================
# 2. VERİYİ YÜKLE VE TEMEL ANALİZ
# ============================================================

def load_and_describe():
    df = pd.read_csv("synthetic_counts.csv")
    print("🔹 Veri boyutu:", df.shape)
    print(df.head())
    print("\n📊 Temel İstatistikler:\n", df.describe())
    return df

# ============================================================
# 3. GÖRSELLEŞTİRME
# ============================================================

def visualize_data(df):
    plt.figure(figsize=(10, 5))
    plt.plot(df["t"], df["counts"], label="Gözlemlenen Sayımlar", color="blue")
    plt.plot(df["t"], df["true_signal"], label="Gerçek Sinyal (model)", color="orange", linestyle="--")
    plt.title("Sentetik Sayım Zaman Serisi")
    plt.xlabel("Zaman (t)")
    plt.ylabel("Counts")
    plt.legend()
    plt.tight_layout()
    plt.savefig("plot_timeseries.png", dpi=300)
    plt.show()
    print("💾 Görsel kaydedildi: plot_timeseries.png")

# ============================================================
# 4. POISSON REGRESYON (EĞİTİM AMAÇLI)
# ============================================================

def poisson_glm(df):
    try:
        import statsmodels.api as sm
        import statsmodels.formula.api as smf
        model = smf.glm(formula="counts ~ true_signal", data=df, family=sm.families.Poisson()).fit()
        print(model.summary())
        print("✅ Poisson GLM başarıyla çalıştı.")
    except Exception as e:
        print("⚠️ Poisson GLM çalıştırılamadı:", e)
        print("Statsmodels paketini kurmak için: pip install statsmodels")

# ============================================================
# 5. BOOTSTRAP ANALİZİ
# ============================================================

def bootstrap_analysis(df, n_boot=1000):
    rng = np.random.default_rng(123)
    medians = [np.median(rng.choice(df["counts"], size=len(df), replace=True)) for _ in range(n_boot)]

    plt.figure(figsize=(8, 4))
    sns.histplot(medians, bins=30, kde=True)
    plt.title("Bootstrap: Counts Medyan Dağılımı")
    plt.xlabel("Medyan Değer")
    plt.tight_layout()
    plt.savefig("plot_bootstrap.png", dpi=300)
    plt.show()
    print("💾 Görsel kaydedildi: plot_bootstrap.png")

# ============================================================
# 6. ANOMALİ TESPİTİ (ISOLATION FOREST)
# ============================================================

def anomaly_detection(df):
    try:
        from sklearn.ensemble import IsolationForest
        model = IsolationForest(contamination=0.03, random_state=42)
        df["anomaly"] = model.fit_predict(df[["counts"]])
        df["anomaly"] = df["anomaly"].apply(lambda x: 1 if x == -1 else 0)

        plt.figure(figsize=(10, 5))
        plt.plot(df["t"], df["counts"], label="Sayım", color="gray")
        anomalies = df[df["anomaly"] == 1]
        plt.scatter(anomalies["t"], anomalies["counts"], color="red", label="Anomali", zorder=5)
        plt.title("Anomali Tespiti (Isolation Forest)")
        plt.xlabel("Zaman (t)")
        plt.ylabel("Counts")
        plt.legend()
        plt.tight_layout()
        plt.savefig("plot_anomalies.png", dpi=300)
        plt.show()
        print("💾 Görsel kaydedildi: plot_anomalies.png")
        print("🔸 Bulunan anomali sayısı:", df['anomaly'].sum())
    except Exception as e:
        print("⚠️ Anomali tespiti başarısız:", e)
        print("Scikit-learn yüklemek için: pip install scikit-learn")

# ============================================================
# 7. ANA ÇALIŞMA AKIŞI
# ============================================================

def main():
    print("🔬 Toryum 232 Dönüşümünün İstatistiksel Modellemesi - Eğitim Projesi")
    df = create_synthetic_data()
    df = load_and_describe()
    visualize_data(df)
    poisson_glm(df)
    bootstrap_analysis(df)
    anomaly_detection(df)
    print("\n🎯 Eğitim tamamlandı. Tüm çıktılar kaydedildi.\n")

if __name__ == "__main__":
    main()